/** @type {import('tailwindcss').Config} */
export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	theme: {
		colors: {
			primary: '#fb7f0c',
			green: '#40c22b',
			blue:'#3C81F3',
			yellow: '#ffca67',
			brown: '#7d3f06',
			gray: '#7d7b7b',
			white: '#ffffff',
			black: '#000000',
			red: '#d2042d',
			light: '#fef2e6',
			light_purple: '#f4ebfc',
			light_pink: '#ffd1df',
			light_yellow: '#e0cda9',
			light_gray: '#d3d3d3',
			light_primary: '#ffddb3',
			light_green: '#ebf9f1',
			super_light_purple: '#f7f6fe',
			pink: '#FA3694',
			primary_dark: '#CE6B0F',
			another_primary: '#ee9a4b',
			info: '#ffc107',
			hero: '#efa37f',
			anotherRed: '#f61818',
		},
	},
	plugins: [],
};
